framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - validation
                    - doctrine_transaction
        routing:
            'App\Message\SendActivityReminderMessage': async
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
