<?php

namespace ContainerAzOxEX6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2AQW8MkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2AQW8Mk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2AQW8Mk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CategorieController::delete' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\CategorieController::edit' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\CategorieController::index' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\CategorieController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CategorieController::show' => ['privates', '.service_locator.j7wOkYK', 'get_ServiceLocator_J7wOkYKService', true],
            'App\\Controller\\DepenseController::delete' => ['privates', '.service_locator.EeEer4R', 'get_ServiceLocator_EeEer4RService', true],
            'App\\Controller\\DepenseController::edit' => ['privates', '.service_locator.EeEer4R', 'get_ServiceLocator_EeEer4RService', true],
            'App\\Controller\\DepenseController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\DepenseController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\DepenseController::show' => ['privates', '.service_locator.2_83HPM', 'get_ServiceLocator_283HPMService', true],
            'App\\Controller\\ReportController::chat' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ReportController::monthlyReport' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController::forgotPassword' => ['privates', '.service_locator.ta0DeOv', 'get_ServiceLocator_Ta0DeOvService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.qrNhk2c', 'get_ServiceLocator_QrNhk2cService', true],
            'App\\Controller\\UserController::resetPassword' => ['privates', '.service_locator.KVWvkFB', 'get_ServiceLocator_KVWvkFBService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CategorieController:delete' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\CategorieController:edit' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\CategorieController:index' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\CategorieController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CategorieController:show' => ['privates', '.service_locator.j7wOkYK', 'get_ServiceLocator_J7wOkYKService', true],
            'App\\Controller\\DepenseController:delete' => ['privates', '.service_locator.EeEer4R', 'get_ServiceLocator_EeEer4RService', true],
            'App\\Controller\\DepenseController:edit' => ['privates', '.service_locator.EeEer4R', 'get_ServiceLocator_EeEer4RService', true],
            'App\\Controller\\DepenseController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\DepenseController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\DepenseController:show' => ['privates', '.service_locator.2_83HPM', 'get_ServiceLocator_283HPMService', true],
            'App\\Controller\\ReportController:chat' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ReportController:monthlyReport' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController:forgotPassword' => ['privates', '.service_locator.ta0DeOv', 'get_ServiceLocator_Ta0DeOvService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.qrNhk2c', 'get_ServiceLocator_QrNhk2cService', true],
            'App\\Controller\\UserController:resetPassword' => ['privates', '.service_locator.KVWvkFB', 'get_ServiceLocator_KVWvkFBService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CategorieController::delete' => '?',
            'App\\Controller\\CategorieController::edit' => '?',
            'App\\Controller\\CategorieController::index' => '?',
            'App\\Controller\\CategorieController::new' => '?',
            'App\\Controller\\CategorieController::show' => '?',
            'App\\Controller\\DepenseController::delete' => '?',
            'App\\Controller\\DepenseController::edit' => '?',
            'App\\Controller\\DepenseController::index' => '?',
            'App\\Controller\\DepenseController::new' => '?',
            'App\\Controller\\DepenseController::show' => '?',
            'App\\Controller\\ReportController::chat' => '?',
            'App\\Controller\\ReportController::monthlyReport' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::forgotPassword' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::login' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::resetPassword' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CategorieController:delete' => '?',
            'App\\Controller\\CategorieController:edit' => '?',
            'App\\Controller\\CategorieController:index' => '?',
            'App\\Controller\\CategorieController:new' => '?',
            'App\\Controller\\CategorieController:show' => '?',
            'App\\Controller\\DepenseController:delete' => '?',
            'App\\Controller\\DepenseController:edit' => '?',
            'App\\Controller\\DepenseController:index' => '?',
            'App\\Controller\\DepenseController:new' => '?',
            'App\\Controller\\DepenseController:show' => '?',
            'App\\Controller\\ReportController:chat' => '?',
            'App\\Controller\\ReportController:monthlyReport' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:forgotPassword' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:login' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:resetPassword' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
