<?php

namespace ContainerAzOxEX6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EeEer4RService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EeEer4R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EeEer4R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'depense' => ['privates', '.errored..service_locator.EeEer4R.App\\Entity\\Depense', NULL, 'Cannot autowire service ".service_locator.EeEer4R": it needs an instance of "App\\Entity\\Depense" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'depense' => 'App\\Entity\\Depense',
            'entityManager' => '?',
        ]);
    }
}
