<?php

namespace ContainerZOVDlsy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepense2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.EeEer4R.App\Entity\Depense' shared service.
     *
     * @return \App\Entity\Depense
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.EeEer4R": it needs an instance of "App\\Entity\\Depense" but this type has been excluded in "config/services.yaml".');
    }
}
