<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZOVDlsy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZOVDlsy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZOVDlsy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZOVDlsy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZOVDlsy\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZOVDlsy',
    'container.build_id' => '14de56a1',
    'container.build_time' => 1734447468,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZOVDlsy');
